/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Class_Core;

import Class_DAO.ChuyenDeDAO;
import Class_DAO.HocVienDAO;
import Class_DAO.KhoaHocDAO;
import Class_DAO.NguoiHocDao;
import Class_Entity.ChuyenDe;
import Class_Entity.HocVien;
import Class_Entity.KhoaHoc;
import Class_Entity.NguoiHoc;
import Class_Helper.Auth;
import Class_Helper.Helper_Connection;
import Class_Helper.MyMessage;
import Class_Helper.XImage;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import java.sql.*;

/**
 *
 * @author 98tae
 */
public class Window_QlHocVien extends javax.swing.JFrame {

    DefaultComboBoxModel<ChuyenDe> model_cbbCD;
    DefaultComboBoxModel<KhoaHoc> model_cbbKH;
    DefaultTableModel modeltbl_HV;
    DefaultTableModel modeltbl_NH;
    ChuyenDeDAO dao_cd;
    KhoaHocDAO dao_kh;
    NguoiHocDao dao_nh;
    HocVienDAO dao_hv;
    List<ChuyenDe> listcd;
    List<KhoaHoc> listkh;
    Connection con;

    public Window_QlHocVien() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setIconImage(XImage.AppImage());
        setLocationRelativeTo(null);
        setTitle("Quản Lý Khóa Học");
        model_cbbCD = (DefaultComboBoxModel) cbbChuyenDe.getModel();
        model_cbbKH = (DefaultComboBoxModel) cbbKhoaHoc.getModel();
        dao_cd = new ChuyenDeDAO();
        dao_kh = new KhoaHocDAO();
        dao_nh = new NguoiHocDao();
        dao_hv = new HocVienDAO();
        listcd = new ArrayList<>();
        listkh = new ArrayList<>();
        modeltbl_HV = (DefaultTableModel) tblHocVienm.getModel();
        modeltbl_NH = (DefaultTableModel) tblnguoihoc.getModel();
        con = Helper_Connection.Connec();
        LoadDataToCBB_ChuyenDe();
        LoadDataToTableHocVien();
        LoadDataToTableNguoiHoc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHocVienm = new javax.swing.JTable();
        btncapnhatdiem = new javax.swing.JButton();
        btnxoakh = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblnguoihoc = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txttimkiem = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnthemvaokh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbbChuyenDe = new javax.swing.JComboBox<>();
        cbbKhoaHoc = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblHocVienm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TT", "Mã HV", "Mã NH", "Họ Tên", "Điểm"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblHocVienm);

        btncapnhatdiem.setText("Cập Nhật Điểm");
        btncapnhatdiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncapnhatdiemActionPerformed(evt);
            }
        });

        btnxoakh.setText("Xóa Khỏi Khóa Học");
        btnxoakh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoakhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 771, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btncapnhatdiem)
                .addGap(18, 18, 18)
                .addComponent(btnxoakh)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncapnhatdiem)
                    .addComponent(btnxoakh))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Học Viên", jPanel1);

        tblnguoihoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NH", "Họ Tên", "Giới Tính", "Ngày Sinh", "SDT", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblnguoihoc);

        jLabel4.setText("Tìm Kiếm");

        jButton1.setText("Tìm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnthemvaokh.setText("Thêm Vào Khóa Học");
        btnthemvaokh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemvaokhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnthemvaokh, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(btnthemvaokh)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Người Học", jPanel2);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Quản Lý Học Viên");

        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Chuyên Đề");

        cbbChuyenDe.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbChuyenDeItemStateChanged(evt);
            }
        });

        cbbKhoaHoc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbKhoaHocItemStateChanged(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Khóa học");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(cbbChuyenDe, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(cbbKhoaHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbChuyenDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbKhoaHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbbChuyenDeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbChuyenDeItemStateChanged
        LoadDataToCBB_KhoaHoc();
    }//GEN-LAST:event_cbbChuyenDeItemStateChanged

    private void btncapnhatdiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncapnhatdiemActionPerformed
        try {
            if (tblHocVienm.getSelectedRow() < 0) {
                return;
            }
            for (int i = 0; i < tblHocVienm.getRowCount(); i++) {
                if (Float.parseFloat(String.valueOf(tblHocVienm.getValueAt(i, 4))) > 10
                        | Float.parseFloat(String.valueOf(tblHocVienm.getValueAt(i, 4))) < 0) {
                    LoadDataToTableHocVien();
                    MyMessage.msgFalse("Điểm Phải Trên 0 và Nhỏ Hơn 10");
                    return;
                }
                if (dao_hv.Update(new HocVien(
                        Integer.parseInt(String.valueOf(tblHocVienm.getValueAt(i, 1))), // MãHV
                        Integer.parseInt(String.valueOf(cbbKhoaHoc.getSelectedItem())), // Mã KH
                        String.valueOf(tblHocVienm.getValueAt(i, 2)),// mã NH
                        Float.parseFloat(String.valueOf(tblHocVienm.getValueAt(i, 4)))))); //Điểm
            }
            MyMessage.msgTrue("Sửa Thành Công");
            LoadDataToTableHocVien();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btncapnhatdiemActionPerformed

    private void btnxoakhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoakhActionPerformed
        int vitri = tblHocVienm.getSelectedRow();
        if (vitri < 0) {
            return;
        }
        try {
            if (dao_hv.Delete(String.valueOf(tblHocVienm.getValueAt(vitri, 1)))) {
                MyMessage.msgTrue("Xóa Thành Công");
                LoadDataToTableHocVien();
            };
        } catch (Exception ex) {
            Logger.getLogger(Window_QlHocVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnxoakhActionPerformed

    private void btnthemvaokhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemvaokhActionPerformed

        try {
            int vitri = tblnguoihoc.getSelectedRow();
            if (vitri < 0) {
                return;
            }
            if (cbbKhoaHoc.getSelectedItem() == null) {
                MyMessage.msgWarning("Không Có Mã Khóa Học");
                return;
            }

            if (dao_hv.Insert(new HocVien(Integer.parseInt(String.valueOf(cbbKhoaHoc.getSelectedItem())),
                    String.valueOf(tblnguoihoc.getValueAt(vitri, 0)),
                    0))) {
                MyMessage.msgTrue("Thêm Thành Công");
                LoadDataToTableHocVien();
            };

        } catch (Exception ex) {
            ex.printStackTrace();
        }


    }//GEN-LAST:event_btnthemvaokhActionPerformed

    private void cbbKhoaHocItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbKhoaHocItemStateChanged
        LoadDataToTableHocVien();
    }//GEN-LAST:event_cbbKhoaHocItemStateChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if (!Auth.isManager()) {
            btnxoakh.setEnabled(false);
        }
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (tblnguoihoc.getRowCount() == 0) {
            return;
        }
        for (int i = 0; i < tblnguoihoc.getRowCount(); i++) {
            if (txttimkiem.getText().trim().equals(String.valueOf(tblnguoihoc.getValueAt(i, 0)).trim())) {
                MyMessage.msgTrue("Người học ở dòng : " + (i + 1));
                return;
            }
        }
        MyMessage.msgFalse("Mã Người Hoc Không Tồn Tại");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window_QlHocVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window_QlHocVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window_QlHocVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window_QlHocVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window_QlHocVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncapnhatdiem;
    private javax.swing.JButton btnthemvaokh;
    private javax.swing.JButton btnxoakh;
    private javax.swing.JComboBox<String> cbbChuyenDe;
    private javax.swing.JComboBox<String> cbbKhoaHoc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblHocVienm;
    private javax.swing.JTable tblnguoihoc;
    private javax.swing.JTextField txttimkiem;
    // End of variables declaration//GEN-END:variables

    private void LoadDataToCBB_ChuyenDe() {
        model_cbbCD.removeAllElements();
        try {
            listcd = dao_cd.SelectAll();
            for (int i = 0; i < listcd.size(); i++) {
                ChuyenDe get = listcd.get(i);
                model_cbbCD.addElement(get);
            }
        } catch (Exception ex) {
            Logger.getLogger(Window_QlHocVien.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void LoadDataToCBB_KhoaHoc() {
        cbbKhoaHoc.removeAllItems();
        String sql = "select * from KhoaHoc\n"
                + "  where MaCD = ?";
        try {
            ChuyenDe cdx = new ChuyenDe();
            cdx = (ChuyenDe) model_cbbCD.getSelectedItem();
            PreparedStatement pt = con.prepareStatement(sql);
            pt.setString(1, cdx.getMaCD());
            ResultSet rs = pt.executeQuery();
            while (rs.next()) {
                KhoaHoc kha = new KhoaHoc(rs.getString(2), rs.getInt(4),
                        rs.getFloat(3), rs.getString(5), rs.getString(6),
                        rs.getString(7), rs.getString(8), rs.getInt(1));
                model_cbbKH.addElement(kha);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void LoadDataToTableHocVien() {
        modeltbl_HV.setRowCount(0);
        String sql = "select MaHV,HocVien.MaNH,HoTen,Diem "
                + "from HocVien join NguoiHoc on HocVien.MaNH = NguoiHoc.MaNH\n"
                + "  where MaKH = ?";
        try {
            int i = 0;
            KhoaHoc khhv = (KhoaHoc) model_cbbKH.getSelectedItem();
            if (khhv == null) {
                return;
            }
            PreparedStatement pt = con.prepareStatement(sql);
            pt.setInt(1, khhv.getMaKH());
            ResultSet rs = pt.executeQuery();
            while (rs.next()) {
                i++;
                Object[] rowData = new Object[]{
                    i,
                    rs.getInt(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getFloat(4)
                };
                modeltbl_HV.addRow(rowData);
            }
            LoadDataToTableNguoiHoc();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void LoadDataToTableNguoiHoc() {
        String sql = "SELECT MaNH, HoTen, GioiTinh,"
                + " convert(varchar, GETDATE(), 103) NgaySinh, "
                + "DienThoai, Email,convert(varchar, GETDATE(), 103)NgayDK, MaNV, GhiChu\n"
                + "from NguoiHoc where MaNH not in (select MaNH from HocVien where MaKH = ?)";
        try {
            modeltbl_NH.setRowCount(0);
            PreparedStatement pt = con.prepareStatement(sql);
            pt.setInt(1, Integer.parseInt(String.valueOf(cbbKhoaHoc.getSelectedItem())));
            ResultSet rs = pt.executeQuery();
            while (rs.next()) {
                String gt = rs.getBoolean(3) ? "Nam" : "Nữ";
                Object[] rowData = new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    gt,
                    rs.getString(4),
                    rs.getString(5),
                    rs.getString(6)
                };
                modeltbl_NH.addRow(rowData);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

}
